spring.application.name=chat-demo

spring.ai.zhipuai.api-key=d4a15a67bd9c4694bb77ce6a1d4f842c.TfydnFOMQDKj6zcx
spring.ai.zhipuai.base-url=https://open.bigmodel.cn/api/paas
spring.ai.zhipuai.chat.options.model=glm-4-air-250414
